### ISSUE TITLE
Your oak example does not compile 

### ISSUE THREAD

**Issue by alvasnet** [denjucks/session#5]
PS C:\work\js\de_no> deno run -A oak.ts
Compile file:///C:/work/js/de_no/oak.ts
error: TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number,
string | undefined>, Record<string, any>>'.
    if (await context.session.get("pageCount") === undefined) {
                      ~~~~~~~
    at file:///C:/work/js/de_no/oak.ts:17:23

TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string
| undefined>, Record<string, any>>'.
        await context.session.set("pageCount", 0);
                      ~~~~~~~
    at file:///C:/work/js/de_no/oak.ts:18:23

TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string
| undefined>, Record<string, any>>'.
        await context.session.set("pageCount", await context.session.get("pageCount") + 1);
                      ~~~~~~~
    at file:///C:/work/js/de_no/oak.ts:20:23

TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string
| undefined>, Record<string, any>>'.
        await context.session.set("pageCount", await context.session.get("pageCount") + 1);
                                                             ~~~~~~~
    at file:///C:/work/js/de_no/oak.ts:20:62

TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string
| undefined>, Record<string, any>>'.
    context.response.body = `Visited page ${await context.session.get("pageCount")} times`;
                                                          ~~~~~~~
    at file:///C:/work/js/de_no/oak.ts:22:59

Found 5 errors.

**Comment by denjucks** [comment]
You need to use the .js file extension, as RouterContext does not allow arbitrary properties to be assigned to it.

**Comment by alvasnet** [comment]
My code does not compile after changing extension from .ts to .js with a message:

PS C:\work\js\de_no> deno run -A oak.js
Compile file:///C:/work/js/de_no/oak.js
error: Uncaught AssertionError: Unexpected skip of the emit.
    at Object.assert ($deno$/util.ts:33:11)
    at compile ($deno$/compiler.ts:1170:7)
    at tsCompilerOnMessage ($deno$/compiler.ts:1338:22)
    at workerMessageRecvCallback ($deno$/runtime_worker.ts:72:33)
    at file:///C:/work/js/de_no/__anonymous__:1:1

**Comment by alvasnet** [comment]
My code is your oak example:

```
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import { Session } from "https://deno.land/x/session/mod.ts";
// deno run -A oak.js
const app = new Application();
// Configuring Session for the Oak framework
const session = new Session({ framework: "oak" });
await session.init();

// Adding the Session middleware. Now every context will include a property
// called session that you can use the get and set functions on
app.use(session.use()(session));
// Creating a Router and using the session
const router = new Router();

router.get("/", async (context) => {
    // Examples of getting and setting variables on a session
    if (await context.session.get("pageCount") === undefined) {
        await context.session.set("pageCount", 0);
    } else {
        await context.session.set("pageCount", await context.session.get("pageCount") + 1);
    }
    context.response.body = `Visited page ${await context.session.get("pageCount")} times`;
});

app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 8000 });

```

**Comment by denjucks** [comment]
I updated the lib so that it should now compile for TS files. Note that for Oak the session is now stored on context.state instead of just on context. See the new example on the readme.

Also the ` error: Uncaught AssertionError: Unexpected skip of the emit.` is not an error due to Session but rather with current versions of deno. Deno v1.0.2 currently should work. Hoping everything is back in order in v1.0.6. Gonna close this issue for now
